import fs from 'node:fs';

const manifest=JSON.parse(fs.readFileSync('manifest.json','utf8'));
let html=manifest.parts.map(p=>fs.readFileSync(p,'utf8')).join('');
const mustReplace=(from,to,label)=>{if(!html.includes(from))throw new Error(`NOVA build contract missing: ${label}`);html=html.replace(from,to)};

mustReplace('<link rel="preload" as="image" href="logo-transparent.png">','<link rel="preload" as="image" href="logo-transparent.png" fetchpriority="high">','logo preload');

const landingRe=/landing\(\)\{return `<section class="landing warehouse-landing">[\s\S]*?<\/section>`\}/;
if(!landingRe.test(html))throw new Error('NOVA build contract missing: landing renderer');
html=html.replace(landingRe,`landing(){return \`<section class="landing warehouse-landing"><div class="brand-lockup"><img class="brand-logo" src="\${LOGO}" width="600" height="127" alt="Servizi Ospedalieri" loading="eager" decoding="sync" fetchpriority="high" onload="this.closest('.warehouse-landing')?.classList.add('brand-ready')" onerror="this.closest('.warehouse-landing')?.classList.add('brand-ready')"></div><div class="warehouse-list"><button class="warehouse-card warehouse-teramo" type="button" data-action="login" aria-label="Accedi a Magazzino Teramo"><span>MAGAZZINO TERAMO</span></button><button class="warehouse-card warehouse-ferrara" type="button" disabled aria-disabled="true"><span>MAGAZZINO FERRARA</span></button><button class="warehouse-card warehouse-lucca" type="button" disabled aria-disabled="true"><span>MAGAZZINO LUCCA</span></button></div></section>\`}`);

mustReplace('data-action="toggle-pin" aria-label="Mostra PIN"','class="pin-toggle" data-action="toggle-pin" aria-label="Mostra PIN" aria-pressed="false"','PIN toggle markup');
mustReplace("openLogin(){const d=document.getElementById('loginDialog'),pin=document.getElementById('loginPin');pin.value='';document.getElementById('loginError').classList.add('hidden');d.showModal();setTimeout(()=>pin.focus(),50)}","openLogin(){const d=document.getElementById('loginDialog'),pin=document.getElementById('loginPin'),toggle=d.querySelector('[data-action=\\\"toggle-pin\\\"]');pin.value='';pin.type='password';if(toggle){toggle.setAttribute('aria-label','Mostra PIN');toggle.setAttribute('aria-pressed','false')}document.getElementById('loginError').classList.add('hidden');d.showModal();setTimeout(()=>pin.focus(),50)}",'login reset');
mustReplace("'toggle-pin':()=>{const p=document.getElementById('loginPin');p.type=p.type==='password'?'text':'password'}","'toggle-pin':()=>{const p=document.getElementById('loginPin'),show=p.type==='password';p.type=show?'text':'password';el.setAttribute('aria-label',show?'Nascondi PIN':'Mostra PIN');el.setAttribute('aria-pressed',show?'true':'false')}",'PIN toggle state');

mustReplace("replaceSheet(wb,name,ws){if(wb.SheetNames.includes(name))wb.Sheets[name]=ws;else X().utils.book_append_sheet(wb,ws,name)}","replaceSheet(wb,name,ws){const previous=wb.Sheets[name],protection=previous?.['!protect'];if(protection)ws['!protect']=clone(protection);if(wb.SheetNames.includes(name))wb.Sheets[name]=ws;else X().utils.book_append_sheet(wb,ws,name)}",'worksheet protection preservation');

mustReplace('<input id="stockQuery" class="field" placeholder="Codice articolo o taglia…">','<input id="stockQuery" class="field stock-query-uppercase" placeholder="CODICE ARTICOLO O TAGLIA…" autocapitalize="characters" autocomplete="off" spellcheck="false" oninput="this.value=this.value.toUpperCase()">','stock query uppercase');
mustReplace('<article class="stock-card"><div><b>','<article class="stock-card"><div class="stock-card-head"><b>','stock result card hierarchy');

/* Durable Master identity. Existing V12 databases receive a deterministic V1 fallback. */
mustReplace('function createEmptyDb(){return {',`const masterIdFor=(filename='',importedAt='')=>{const at=String(importedAt||nowIso()),day=at.slice(0,10).replace(/\\D/g,'')||new Date().toISOString().slice(0,10).replace(/-/g,''),basis=String(filename||'MASTER')+'|'+at;let h=2166136261;for(let i=0;i<basis.length;i++){h^=basis.charCodeAt(i);h=Math.imul(h,16777619)}return 'MST-'+day+'-'+(h>>>0).toString(16).toUpperCase().padStart(8,'0').slice(0,6)};\n\nfunction createEmptyDb(){return {`,'master identity helper');
mustReplace("master:{rows:[],excelRows:[],filename:'',sheetName:'MAGAZZINO',importedAt:null,headerRow:0,columns:{},mode:'wide',source:'NOVA'},","master:{rows:[],excelRows:[],filename:'',sheetName:'MAGAZZINO',importedAt:null,headerRow:0,columns:{},mode:'wide',source:'NOVA',masterId:'',version:0,versionAt:null},",'master metadata schema');
mustReplace("const bytes=await file.arrayBuffer(),wb=X().read(bytes,{type:'array',cellDates:true,cellStyles:true}),parsed=parseMaster(wb),nova=readChunkSheet(wb,'NOVA_DATI','SO_MAGAZZINO_NOVA_V1'),legacy=readChunkSheet(wb,'APP_DATI','SO_WAREHOUSE_APP_DATA_V3');\n    let next;","const bytes=await file.arrayBuffer(),wb=X().read(bytes,{type:'array',cellDates:true,cellStyles:true}),parsed=parseMaster(wb),nova=readChunkSheet(wb,'NOVA_DATI','SO_MAGAZZINO_NOVA_V1'),legacy=readChunkSheet(wb,'APP_DATI','SO_WAREHOUSE_APP_DATA_V3'),importedAt=nowIso();\n    let next;",'master import timestamp');
mustReplace("next.master={...createEmptyDb().master,...(next.master||{}),rows:hiddenBaseline.length?hiddenBaseline:parsed.rows,excelRows:parsed.rows,filename:file.name,sheetName:parsed.sheetName,importedAt:nowIso(),headerRow:parsed.headerRow,columns:parsed.columns,mode:parsed.mode,source:'NOVA_REIMPORT'};","next.master={...createEmptyDb().master,...(next.master||{}),rows:hiddenBaseline.length?hiddenBaseline:parsed.rows,excelRows:parsed.rows,filename:file.name,sheetName:parsed.sheetName,importedAt,headerRow:parsed.headerRow,columns:parsed.columns,mode:parsed.mode,source:'NOVA_REIMPORT',masterId:next.master?.masterId||masterIdFor(file.name,importedAt),version:Math.max(1,Number(next.master?.version)||1),versionAt:next.master?.versionAt||next.master?.importedAt||importedAt};",'NOVA master identity restore');
mustReplace("next.master={...next.master,rows:parsed.rows,excelRows:parsed.rows,filename:file.name,sheetName:parsed.sheetName,importedAt:nowIso(),headerRow:parsed.headerRow,columns:parsed.columns,mode:parsed.mode,source:'REMOTO_XLSX_MIGRATION'};","next.master={...next.master,rows:parsed.rows,excelRows:parsed.rows,filename:file.name,sheetName:parsed.sheetName,importedAt,headerRow:parsed.headerRow,columns:parsed.columns,mode:parsed.mode,source:'REMOTO_XLSX_MIGRATION',masterId:masterIdFor(file.name,importedAt),version:1,versionAt:importedAt};",'REMOTO master identity');
mustReplace("next.master={...next.master,rows:parsed.rows,excelRows:parsed.rows,filename:file.name,sheetName:parsed.sheetName,importedAt:nowIso(),headerRow:parsed.headerRow,columns:parsed.columns,mode:parsed.mode,source:'FRESH_IMPORT'};","next.master={...next.master,rows:parsed.rows,excelRows:parsed.rows,filename:file.name,sheetName:parsed.sheetName,importedAt,headerRow:parsed.headerRow,columns:parsed.columns,mode:parsed.mode,source:'FRESH_IMPORT',masterId:masterIdFor(file.name,importedAt),version:1,versionAt:importedAt};",'fresh master identity');
mustReplace("next.master={...next.master,rows:current,excelRows:legacyExcelRows.length?legacyExcelRows:current,source:'REMOTO_MIGRATION_BASELINE',importedAt:nowIso()};","next.master={...next.master,rows:current,excelRows:legacyExcelRows.length?legacyExcelRows:current,source:'REMOTO_MIGRATION_BASELINE',importedAt:nowIso(),masterId:next.master.masterId||masterIdFor(next.master.filename||'REMOTO',next.master.importedAt||nowIso()),version:Math.max(1,Number(next.master.version)||1),versionAt:next.master.versionAt||next.master.importedAt||nowIso()};",'local legacy master identity');
mustReplace('    this.updateMagazine(wb);',"    const meta=this.store.db.master,exportedAt=nowIso();if(!meta.masterId)meta.masterId=masterIdFor(meta.filename,meta.importedAt||exportedAt);meta.version=Math.max(1,Number(meta.version)||1)+1;meta.versionAt=exportedAt;\n    this.updateMagazine(wb);",'master version increment before export');
mustReplace("const exportedAudit=this.domain.audit.record('MASTER_EXPORTED','MASTER',name,null,{name});","const exportedAudit=this.domain.audit.record('MASTER_EXPORTED','MASTER',name,null,{name,masterId:this.store.db.master.masterId,version:this.store.db.master.version});",'master export audit identity');
mustReplace("const importedAudit=this.domain.audit.record('MASTER_IMPORTED','MASTER',file.name,null,{rows:parsed.rows.length,source:next.master.source});","const importedAudit=this.domain.audit.record('MASTER_IMPORTED','MASTER',file.name,null,{rows:parsed.rows.length,source:next.master.source,masterId:next.master.masterId,version:next.master.version});",'master import audit identity');

const masterRe=/  master\(\)\{if\(!this\.require\('MASTER'\)\)return'';[\s\S]*?\n\n  receivingHome\(\)\{/;
if(!masterRe.test(html))throw new Error('NOVA build contract missing: master detail renderer');
html=html.replace(masterRe,`  master(){if(!this.require('MASTER'))return'';const m=this.store.db.master,ready=this.masterReady(),hasLegacy=this.excel.legacyAvailable(),masterId=ready?(m.masterId||masterIdFor(m.filename,m.importedAt)):'' ,version=ready?Math.max(1,Number(m.version)||1):0,versionAt=m.versionAt||m.importedAt;return \`\${this.sectionTitle('DATI','Master Excel')}<section class="card"><div class="master-detail-head">\${svg('excel')}<div><h2>\${ready?esc(m.filename):'Nessun Master importato'}</h2><p>\${ready?\`\${m.rows.length} righe normalizzate · \${m.source}\`:'Importa il file .xlsx ufficiale.'}</p></div></div>\${ready?\`<div class="master-version-card"><div class="master-id"><span>ID MASTER</span><b>\${esc(masterId)}</b></div><div><span>VERSIONE</span><b>V\${version}</b></div><div><span>VERSIONE CREATA</span><b>\${fmtDateTime(versionAt)}</b></div><div><span>IMPORTATO</span><b>\${fmtDateTime(m.importedAt)}</b></div><div><span>ORIGINE</span><b>\${esc(m.source||'—')}</b></div></div><div class="info-box">Il Master è la base delle giacenze. NOVA registra le operazioni successive in un unico ledger e aggiorna il workbook durante l’export.</div>\`:''}<button class="primary" data-action="master-import">\${ready?'SOSTITUISCI / REIMPORTA':'IMPORTA MASTER EXCEL'}</button>\${ready?\`<button class="success" data-action="master-export">ESPORTA MASTER AGGIORNATO</button>\`:''}\${!ready&&hasLegacy?\`<div class="legacy-box"><b>Dati REMOTO trovati su questo dispositivo</b><span>Puoi migrare una copia in NOVA. REMOTO non viene modificato.</span><button class="soft" data-action="legacy-migrate">MIGRA COPIA DA REMOTO</button></div>\`:''}</section>\`}\n\n  receivingHome(){`);

/* Replace native Android stock select with a first-party NOVA picker. */
const sourceSelectRe=/  sourceSelect\(id='sourceSelect'\)\{[\s\S]*?\n  issue\(\)\{/;
if(!sourceSelectRe.test(html))throw new Error('NOVA build contract missing: native source selector');
html=html.replace(sourceSelectRe,`  sourcePickerTriggerMarkup(r){if(!r)return '<span><b>NESSUNA GIACENZA DISPONIBILE</b><small>Non ci sono articoli selezionabili.</small></span><span class="source-picker-chevron">›</span>';const loc=r.location===CONFIG.receivingLocation?'AREA RICEVIMENTO':\`Fila/Scaffale \${esc(r.location||'—')}\`;return \`<span><b>\${esc(r.article)}\${r.size?\` · \${esc(r.size)}\`:''}</b><small>\${r.quantity} pezzi · \${loc} · Bancale \${esc(r.pallet||'—')}</small></span><span class="source-picker-chevron">›</span>\`}\n  sourceSelect(id='sourceSelect'){const rows=this.domain.stock.positive(),r=rows[0]||null,key=r?bucketKey(r):'';return \`<div class="source-picker-field"><input id="\${id}" type="hidden" value="\${esc(key)}"><button id="\${id}-trigger" type="button" class="source-picker-trigger" data-action="source-picker-open" data-target="\${id}" \${r?'':'disabled'}>\${this.sourcePickerTriggerMarkup(r)}</button></div>\`}\n  openSourcePicker(id){const input=document.getElementById(id),d=document.getElementById('sourcePickerDialog');if(!input||!d)return;this.sourcePickerTarget=id;const q=document.getElementById('sourcePickerSearch');if(q)q.value='';this.renderSourcePicker('');d.showModal();setTimeout(()=>q?.focus(),80)}\n  closeSourcePicker(){const d=document.getElementById('sourcePickerDialog');if(d?.open)d.close();this.sourcePickerTarget=''}\n  renderSourcePicker(query=''){const host=document.getElementById('sourcePickerList');if(!host)return;const q=norm(query),current=document.getElementById(this.sourcePickerTarget||'')?.value||'',rows=this.domain.stock.positive().filter(r=>!q||norm(\`\${r.article} \${r.size} \${r.state} \${r.location} \${r.pallet}\`).includes(q));host.innerHTML=rows.length?rows.map((r,i)=>{const key=bucketKey(r),loc=r.location===CONFIG.receivingLocation?'AREA RICEVIMENTO':\`Fila/Scaffale \${esc(r.location||'—')}\`;return \`<button type="button" class="source-picker-item \${i%2?'tone-cream':'tone-green'} \${key===current?'selected':''}" data-action="source-picker-choose" data-key="\${esc(key)}"><span class="source-picker-copy"><b>\${esc(r.article)}\${r.size?\` · \${esc(r.size)}\`:''}</b><small><span>\${esc(r.state)}</span><span>\${loc}</span><span>Bancale \${esc(r.pallet||'—')}</span></small></span><strong class="source-picker-qty">\${r.quantity}</strong></button>\`}).join(''):'<div class="source-picker-empty">Nessuna giacenza corrisponde alla ricerca.</div>'}\n  chooseSource(key){const input=document.getElementById(this.sourcePickerTarget||''),r=this.domain.stock.findByKey(key);if(!input||!r)return;input.value=key;const trigger=document.getElementById(\`\${this.sourcePickerTarget}-trigger\`);if(trigger)trigger.innerHTML=this.sourcePickerTriggerMarkup(r);this.closeSourcePicker()}\n  issue(){`);

mustReplace('<div id="toastHost" class="toast-host"></div>',`<dialog id="sourcePickerDialog" class="source-picker-dialog"><div class="source-picker-shell"><header class="source-picker-head"><button type="button" class="source-picker-back" data-action="source-picker-close" aria-label="Torna indietro">‹</button><div><span>GIACENZE DISPONIBILI</span><b>Seleziona articolo</b></div></header><div class="source-picker-search"><input id="sourcePickerSearch" class="field" placeholder="CERCA CODICE, TAGLIA, BANCALE…" autocapitalize="characters" autocomplete="off" spellcheck="false"></div><div id="sourcePickerList" class="source-picker-list"></div></div></dialog>\n\n<div id="toastHost" class="toast-host"></div>`,'source picker dialog');
mustReplace("if(el.id==='registryQuery')this.renderRegistryResults();if(el.id==='loginPin'){","if(el.id==='registryQuery')this.renderRegistryResults();if(el.id==='sourcePickerSearch')this.renderSourcePicker(el.value);if(el.id==='loginPin'){",'source picker live search');
mustReplace('const map={back:',"const map={'source-picker-open':()=>this.openSourcePicker(el.dataset.target),'source-picker-close':()=>this.closeSourcePicker(),'source-picker-choose':()=>this.chooseSource(el.dataset.key),back:",'source picker actions');
mustReplace("'master-export':async()=>{const n=await this.excel.export();this.toast(`${n} esportato.`)}","'master-export':async()=>{const n=await this.excel.export();this.toast(`${n} esportato.`);this.renderView()}",'refresh master version after export');

if(!html.includes('bundle/mobile-v4.css'))html=html.replace('</head>','<link rel="stylesheet" href="bundle/mobile-v4.css?v=20260828-v6"></head>');
else html=html.replace(/bundle\/mobile-v4\.css\?v=[^"']+/g,'bundle/mobile-v4.css?v=20260828-v6');
if(!html.includes('bundle/landing-brand-v7.css'))html=html.replace('</head>','<link rel="stylesheet" href="bundle/landing-brand-v7.css?v=20260828-v7"></head>');
else html=html.replace(/bundle\/landing-brand-v7\.css\?v=[^"']+/g,'bundle/landing-brand-v7.css?v=20260828-v7');
if(!html.includes('bundle/landing-brand-v8.css'))html=html.replace('</head>','<link rel="stylesheet" href="bundle/landing-brand-v8.css?v=20260828-v8"></head>');
else html=html.replace(/bundle\/landing-brand-v8\.css\?v=[^"']+/g,'bundle/landing-brand-v8.css?v=20260828-v8');
if(!html.includes('bundle/stock-ux-v11.css'))html=html.replace('</head>','<link rel="stylesheet" href="bundle/stock-ux-v11.css?v=20260831-v11"></head>');
else html=html.replace(/bundle\/stock-ux-v11\.css\?v=[^"']+/g,'bundle/stock-ux-v11.css?v=20260831-v11');
if(!html.includes('bundle/article-palette-v12.css'))html=html.replace('</head>','<link rel="stylesheet" href="bundle/article-palette-v12.css?v=20260831-v12"></head>');
else html=html.replace(/bundle\/article-palette-v12\.css\?v=[^"']+/g,'bundle/article-palette-v12.css?v=20260831-v12');
if(!html.includes('bundle/ux-system-v13.css'))html=html.replace('</head>','<link rel="stylesheet" href="bundle/ux-system-v13.css?v=20260831-v13"></head>');
else html=html.replace(/bundle\/ux-system-v13\.css\?v=[^"']+/g,'bundle/ux-system-v13.css?v=20260831-v13');
if(!html.includes('bundle/ui-sound-v8.js'))html=html.replace('</body>','<script src="bundle/ui-sound-v8.js?v=20260828-v10"></script></body>');
else html=html.replace(/bundle\/ui-sound-v8\.js\?v=[^"']+/g,'bundle/ui-sound-v8.js?v=20260828-v10');

fs.writeFileSync('index.html',html,'utf8');
console.log(`NOVA V13 source picker + sage/cream system + Master identity generated: ${Buffer.byteLength(html)} bytes`);
