import fs from 'node:fs';

await import('./build-v15.mjs');

let html=fs.readFileSync('index.html','utf8');
const mustReplace=(from,to,label)=>{if(!html.includes(from))throw new Error(`NOVA V16 build contract missing: ${label}`);html=html.replace(from,to)};
const mustRegex=(re,to,label)=>{if(!re.test(html))throw new Error(`NOVA V16 build contract missing: ${label}`);html=html.replace(re,to)};

mustReplace('</head>','<link rel="stylesheet" href="bundle/request-v16.css?v=20260901-v16"></head>','V16 stylesheet');
mustReplace('<title>Magazzino NOVA · Teramo · V15</title>','<title>Magazzino NOVA · Teramo · V16</title>','V16 title');

/* Domain: ADMIN may permanently remove only a request that has never moved stock. Audit remains immutable. */
mustReplace("  closeRemaining(id,reason=''){","  deleteUnworked(id,reason=''){if(PROFILES[this.auth.user]?.role!=='ADMIN')throw new Error('Solo l’amministratore può eliminare definitivamente una richiesta.');const idx=this.store.db.requests.findIndex(x=>x.id===id);if(idx<0)throw new Error('Richiesta non trovata.');const r=this.store.db.requests[idx],s=this.summary(r);if(s.delivered>0||(r.deliveries||[]).length)throw new Error('La richiesta è già stata lavorata e non può essere eliminata.');if(['COMPLETATA','CHIUSA PARZIALE'].includes(r.status))throw new Error('La richiesta è già chiusa e non può essere eliminata.');const before=clone(r),at=nowIso(),why=String(reason||'').trim();this.audit.record('REQUEST_DELETED','REQUEST',id,before,null,{reason:why,deletedAt:at,deletedBy:this.auth.user});for(const n of this.store.db.notifications||[]){if(n.entityType==='REQUEST'&&n.entityId===id){n.readAt=n.readAt||at;n.entityType='';n.entityId=''}}this.store.db.requests.splice(idx,1);this.store.save('request:delete');return{id,deletedAt:at,deletedBy:this.auth.user}}\n  closeRemaining(id,reason=''){","Request hard delete domain");

const execute=`  executePendingOperation(){const op=this.pendingOperation;if(!op)return;const reason=document.getElementById('operationConfirmReason')?.value||'';if(op.kind==='receipt-cancel'){this.domain.receiving.cancel(op.id,reason);this.toast('Entrata annullata e giacenza stornata.');this.dismissOperation();this.router.go('receipt-detail',{id:op.id});return}if(op.kind==='request-cancel'){this.domain.requests.cancel(op.id,reason);this.toast('Richiesta annullata.');this.dismissOperation();this.router.go('request-detail',{id:op.id});return}if(op.kind==='request-delete'){this.domain.requests.deleteUnworked(op.id,reason);this.toast('Richiesta eliminata. Lo storico resta nell’Audit.');this.dismissOperation();this.router.go('requests-process');return}if(op.kind==='request-close'){this.domain.requests.closeRemaining(op.id,reason);this.toast('Residuo richiesta chiuso.');this.dismissOperation();this.router.go('request-detail',{id:op.id});return}}`;
mustRegex(/  executePendingOperation\(\)\{[^\n]*\}\n  openLogin/,`${execute}\n  openLogin`,'Request delete confirm execution');

mustReplace("'request-cancel':()=>this.askOperation('request-cancel',el.dataset.id,'Annulla richiesta','La richiesta verrà marcata come ANNULLATA e resterà nello storico. Nessuna giacenza verrà modificata.'),'request-close':", "'request-cancel':()=>this.askOperation('request-cancel',el.dataset.id,'Annulla richiesta','La richiesta verrà marcata come ANNULLATA e resterà nello storico. Nessuna giacenza verrà modificata.'),'request-delete':()=>this.askOperation('request-delete',el.dataset.id,'Elimina richiesta','Questa azione rimuove definitivamente la richiesta dall’elenco. È consentita solo se non è mai stata lavorata e non modifica alcuna giacenza. Una copia completa resterà nell’Audit.'),'request-close':",'Request delete action');

const requestCard=`  requestCard(r,mode){const s=this.domain.requests.summary(r),terminal=['ANNULLATA','CHIUSA PARZIALE'].includes(r.status),statusClass=r.status==='ANNULLATA'?'cancelled':r.status==='CHIUSA PARZIALE'?'closed':r.status==='COMPLETATA'?'done':r.status==='PARZIALE'?'partial':'',canDelete=PROFILES[this.auth.user]?.role==='ADMIN'&&s.delivered===0&&!['COMPLETATA','CHIUSA PARZIALE'].includes(r.status),primaryAction=mode==='PROCESS'&&!terminal?'request-pick':'request-open',primaryLabel=mode==='PROCESS'&&!terminal?'PREPARA':'APRI DETTAGLIO';return \`<article class="request-card \${r.status==='ANNULLATA'?'is-cancelled':''}"><div class="request-head"><div><span>\${r.id}</span><h2>\${esc(r.destination)}</h2><p>\${fmtDateTime(r.requestedAt)} · \${esc(r.operator)}</p></div><em class="status-pill \${statusClass}">\${r.status}</em></div><div class="progress"><i style="width:\${s.percent}%"></i></div><div class="metrics"><div><b>\${s.requested}</b><span>Cartoni richiesti</span></div><div><b>\${s.delivered}</b><span>Cartoni presi</span></div><div><b>\${s.remaining}</b><span>Cartoni residui</span></div></div><div class="request-card-actions"><button class="soft request-primary" data-action="\${primaryAction}" data-id="\${r.id}">\${primaryLabel}</button>\${canDelete?\`<button class="request-delete-btn" data-action="request-delete" data-id="\${r.id}" aria-label="Elimina richiesta \${r.id}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h18M8 6V4h8v2M6 6l1 14h10l1-14M10 10v6M14 10v6"/></svg><span>ELIMINA</span></button>\`:''}</div></article>\`}`;
mustRegex(/  requestCard\(r,mode\)\{[^\n]*\}\n  requestDetail/,`${requestCard}\n  requestDetail`,'Request card actions');

const requestPick=`  requestPick(id){const r=this.store.db.requests.find(x=>x.id===id);if(!r)return this.emptyPage('Richiesta non trovata.');return \`\${this.sectionTitle('PRELIEVO',r.id,'Cartoni = avanzamento richiesta · Pezzi = quantità sottratta dal Master')}<div id="requestPickSources" data-request="\${r.id}"></div><details class="extra-pick-collapsible"><summary><span class="extra-pick-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M4 7.5 12 3l8 4.5v9L12 21l-8-4.5v-9Z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9M9 5l8 4.5"/></svg></span><span class="extra-pick-copy"><b>Materiale non richiesto</b><small>Facoltativo · apri solo se devi scaricare materiale extra.</small></span><span class="extra-pick-chevron" aria-hidden="true">⌄</span></summary><div class="extra-pick-body"><p class="hint">Verrà scaricato dalla giacenza ma non modifica i cartoni richiesti.</p><label>Giacenza\${this.sourceSelect('extraPickSource')}</label><div class="two"><label>Cartoni<input id="extraPickCartons" type="number" min="0" value="0" class="field"></label><label>Pezzi<input id="extraPickPieces" type="number" min="0" value="0" class="field"></label></div></div></details><label>Note consegna<textarea id="requestPickNote" class="field textarea"></textarea></label><div class="workflow-actions"><button class="workflow-cancel" data-action="workflow-back">ANNULLA</button><button class="success" data-action="request-pick-save" data-id="\${r.id}">CONFERMA CARTONI E SCARICA PEZZI</button></div>\`}`;
mustRegex(/  requestPick\(id\)\{[^\n]*\}\n  renderRequestPickSources/,`${requestPick}\n  renderRequestPickSources`,'Collapsible extra material');

fs.writeFileSync('index.html',html,'utf8');
console.log(`NOVA V16 request UX generated: ${Buffer.byteLength(html)} bytes`);
