/* Modalità MASTER EXCEL locale: importazione -> lavoro -> export del workbook aggiornato.
   Mantiene il foglio MAGAZZINO come fonte operativa e aggiunge storico leggibile + stato app nascosto. */
(function installLocalMasterMode(){
  'use strict';

  const LM_VERSION=3;
  const META_KEY='so_local_master_meta_v3';
  const IDB_NAME='so_warehouse_files_v1';
  const IDB_STORE='files';
  const IDB_MASTER_KEY='active-master-xlsx';
  const DATA_SHEET='APP_DATI';
  const MOV_SHEET='REGISTRO_MOVIMENTI';
  const DOC_SHEET='SCARICHI';
  const REQ_SHEET='RICHIESTE';
  const VALID_MASTER_STATES=['NUOVO','SCARICATO','USATO'];
  let pendingImport=null;
  let importBypass=false;
  let panelReady=false;

  function clone(v){return typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v))}
  function norm(v){return String(v??'').trim().toUpperCase()}
  function html(v){return typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function readMeta(){try{return {...JSON.parse(localStorage.getItem(META_KEY)||'{}')}}catch{return {}}}
  function writeMeta(patch){const next={...readMeta(),...patch,version:LM_VERSION};localStorage.setItem(META_KEY,JSON.stringify(next));return next}
  function clearMeta(){localStorage.removeItem(META_KEY)}
  function fmtWhen(v){if(!v)return '—';try{return new Date(v).toLocaleString('it-IT',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}catch{return '—'}}
  function isoNow(){return new Date().toISOString()}
  function fileStamp(d=new Date()){const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}_${z(d.getHours())}${z(d.getMinutes())}`}
  function dateTimeText(v){if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleString('it-IT',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'})}
  function toast(msg,type='success'){if(typeof warehouseToast==='function')warehouseToast(msg,type);else console.log('[MASTER]',msg)}

  function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(IDB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(IDB_STORE))r.result.createObjectStore(IDB_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
  async function idbPut(key,value){const d=await openDb();return new Promise((resolve,reject)=>{const tx=d.transaction(IDB_STORE,'readwrite');tx.objectStore(IDB_STORE).put(value,key);tx.oncomplete=()=>{d.close();resolve()};tx.onerror=()=>{const e=tx.error;d.close();reject(e)}})}
  async function idbGet(key){const d=await openDb();return new Promise((resolve,reject)=>{const tx=d.transaction(IDB_STORE,'readonly'),r=tx.objectStore(IDB_STORE).get(key);r.onsuccess=()=>{const v=r.result;d.close();resolve(v)};r.onerror=()=>{const e=r.error;d.close();reject(e)}})}
  async function idbDelete(key){const d=await openDb();return new Promise((resolve,reject)=>{const tx=d.transaction(IDB_STORE,'readwrite');tx.objectStore(IDB_STORE).delete(key);tx.oncomplete=()=>{d.close();resolve()};tx.onerror=()=>{const e=tx.error;d.close();reject(e)}})}

  function ensureDialog(){let dlg=document.getElementById('lmDialog');if(dlg)return dlg;dlg=document.createElement('dialog');dlg.id='lmDialog';dlg.className='lmDialog';dlg.innerHTML='<div class="lmDialogIcon" id="lmDialogIcon">✓</div><h2 id="lmDialogTitle"></h2><div id="lmDialogBody" class="lmDialogBody"></div><div id="lmDialogActions" class="lmDialogActions"></div>';document.body.appendChild(dlg);return dlg}
  function modal({title,body,icon='✓',actions=[{label:'CHIUDI',value:'close',kind:'primary'}]}){return new Promise(resolve=>{const dlg=ensureDialog(),titleEl=document.getElementById('lmDialogTitle'),bodyEl=document.getElementById('lmDialogBody'),iconEl=document.getElementById('lmDialogIcon'),actionsEl=document.getElementById('lmDialogActions');titleEl.textContent=title;bodyEl.innerHTML=body;iconEl.textContent=icon;actionsEl.innerHTML='';let settled=false;const finish=v=>{if(settled)return;settled=true;try{dlg.close()}catch{}resolve(v)};for(const a of actions){const b=document.createElement('button');b.type='button';b.className=`lmAction ${a.kind||'soft'}`;b.textContent=a.label;b.onclick=()=>finish(a.value);actionsEl.appendChild(b)}dlg.oncancel=e=>{e.preventDefault();finish(actions.find(a=>a.value==='cancel')?.value||actions[0]?.value||'close')};dlg.showModal()})}

  function currentMasterLoaded(){return !!(db?.master?.rows?.length&&db.master.filename)}
  function auditCountSince(iso){if(!iso)return (db?.audits||[]).length;const t=new Date(iso).getTime();return (db?.audits||[]).filter(a=>new Date(a.at||0).getTime()>t).length}
  function dirtyCount(){const m=readMeta();const baseline=m.lastExportAt||m.importedAt;return auditCountSince(baseline)}
  function recordCounts(){return {moves:(db?.movements||[]).length,docs:(db?.documents||[]).length,reqs:(db?.requests||[]).length}}

  function ensurePanel(){if(panelReady&&document.getElementById('localMasterPanel'))return;const home=document.getElementById('home'),grid=home?.querySelector('.homeGrid');if(!home||!grid)return;let panel=document.getElementById('localMasterPanel');if(!panel){panel=document.createElement('section');panel.id='localMasterPanel';panel.className='lmPanel';panel.innerHTML=`
      <div class="lmPanelTop">
        <div><div class="lmEyebrow">MASTER EXCEL</div><div class="lmTitle" id="lmTitle">Nessun master caricato</div></div>
        <span id="lmState" class="lmPill offline">NON CARICATO</span>
      </div>
      <div id="lmSub" class="lmSub">Importa il file .xlsx ufficiale prima di iniziare le operazioni.</div>
      <div id="lmStats" class="lmStats hidden"></div>
      <div id="lmPending" class="lmPending hidden"></div>
      <div class="lmButtons">
        <button id="lmImportBtn" class="lmBtn primary" type="button">📥 IMPORTA MASTER</button>
        <button id="lmExportBtn" class="lmBtn success hidden" type="button">📤 ESPORTA MASTER AGGIORNATO</button>
        <button id="lmManageBtn" class="lmBtn soft hidden" type="button">⚙ GESTISCI</button>
      </div>`;
      grid.parentNode.insertBefore(panel,grid);
      panel.querySelector('#lmImportBtn').onclick=()=>LocalMaster.chooseImport();
      panel.querySelector('#lmExportBtn').onclick=()=>LocalMaster.exportUpdatedMaster();
      panel.querySelector('#lmManageBtn').onclick=()=>LocalMaster.manage();
    }
    panelReady=true;renderPanel();
  }

  async function renderPanel(){ensurePanel();const title=document.getElementById('lmTitle'),state=document.getElementById('lmState'),sub=document.getElementById('lmSub'),stats=document.getElementById('lmStats'),pending=document.getElementById('lmPending'),imp=document.getElementById('lmImportBtn'),exp=document.getElementById('lmExportBtn'),manage=document.getElementById('lmManageBtn');if(!title)return;const loaded=currentMasterLoaded(),m=readMeta();let hasBytes=false;try{hasBytes=!!(await idbGet(IDB_MASTER_KEY))}catch{}document.body.classList.toggle('lmNoMaster',!loaded);
    if(!loaded){title.textContent='Nessun master caricato';state.className='lmPill offline';state.textContent='NON CARICATO';sub.textContent='Importa il file .xlsx ufficiale prima di iniziare le operazioni.';stats.classList.add('hidden');pending.classList.add('hidden');imp.textContent='📥 IMPORTA MASTER';exp.classList.add('hidden');manage.classList.add('hidden');return}
    const dirty=dirtyCount(),c=recordCounts();title.textContent=db.master.filename||'Confezionato_MASTER.xlsx';state.className='lmPill online';state.textContent='PRONTO';sub.textContent=`Importato ${fmtWhen(db.master.imported_at)} · ${m.excelRows||'—'} righe Excel${hasBytes?'':' · file originale da ricollegare'}`;stats.classList.remove('hidden');stats.innerHTML=`<div><b>${c.moves}</b><span>Movimenti</span></div><div><b>${c.docs}</b><span>Scarichi</span></div><div><b>${c.reqs}</b><span>Richieste</span></div>`;pending.classList.remove('hidden');pending.className=`lmPending ${dirty?'warn':'ok'}`;pending.innerHTML=dirty?`<b>${dirty}</b> modifiche dall’ultimo export`:`✓ Nessuna modifica in attesa di export${m.lastExportAt?` · ultimo ${fmtWhen(m.lastExportAt)}`:''}`;imp.textContent='↻ SOSTITUISCI / REIMPORTA';exp.classList.toggle('hidden',!hasBytes);manage.classList.remove('hidden');if(!hasBytes){state.className='lmPill warn';state.textContent='DA RICOLLEGARE';pending.className='lmPending warn';pending.textContent='Il database locale è presente, ma manca il file Excel originale. Reimporta lo stesso master per poter esportare.'}
  }

  function requireMaster(){if(!currentUser){openLogin();return false}if(currentMasterLoaded())return true;modal({title:'Prima importa il Master Excel',icon:'📥',body:'<p>Per evitare dati scollegati dal file ufficiale, CARICA, SCARICA, CERCA, MODIFICA e RICHIESTE sono disponibili solo dopo aver importato il master .xlsx.</p>',actions:[{label:'ANNULLA',value:'cancel',kind:'soft'},{label:'IMPORTA MASTER',value:'import',kind:'primary'}]}).then(v=>{if(v==='import')LocalMaster.chooseImport()});return false}

  async function chooseImport(){if(!currentUser){openLogin();return}const dirty=dirtyCount();if(currentMasterLoaded()&&dirty>0){const v=await modal({title:'Modifiche non ancora esportate',icon:'⚠',body:`<p>Ci sono <b>${dirty}</b> modifiche effettuate dopo l’ultimo export.</p><p>Se sostituisci il master adesso potresti perdere il lavoro non esportato.</p>`,actions:[{label:'ANNULLA',value:'cancel',kind:'soft'},{label:'ESPORTA PRIMA',value:'export',kind:'success'},{label:'IMPORTA COMUNQUE',value:'force',kind:'danger'}]});if(v==='cancel')return;if(v==='export'){await LocalMaster.exportUpdatedMaster();return}if(v!=='force')return}
    const input=document.getElementById('masterInput');if(!input)return toast('Selettore Master Excel non disponibile.','error');importBypass=true;input.click();setTimeout(()=>{importBypass=false},1000)
  }

  function parseEmbeddedDb(wb){const ws=wb?.Sheets?.[DATA_SHEET];if(!ws)return null;const a=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});if(String(a?.[0]?.[0]||'')!=='SO_WAREHOUSE_APP_DATA_V3')return null;const chunks=[];for(let i=4;i<a.length;i++)if(a[i]?.[0])chunks.push(String(a[i][0]));if(!chunks.length)return null;try{const p=JSON.parse(chunks.join(''));return p?.db&&Array.isArray(p.db.movements)?p:null}catch(e){console.warn('APP_DATI non leggibile',e);return null}}

  function restoreEmbeddedDb(payload,importedMaster){if(!payload?.db)return false;const saved=payload.db,base=typeof blankDb==='function'?blankDb():{version:3,master:{rows:[]},movements:[],documents:[],requests:[],audits:[],counters:{scarico:0,request:0}};db={...base,...saved,master:importedMaster,counters:{...base.counters,...(saved.counters||{})},movements:Array.isArray(saved.movements)?saved.movements:[],documents:Array.isArray(saved.documents)?saved.documents:[],requests:Array.isArray(saved.requests)?saved.requests:[],audits:Array.isArray(saved.audits)?saved.audits:[]};saveDb();return true}

  function resetOperationalHistoryKeepMaster(importedMaster){const base=blankDb();db={...base,master:importedMaster};db.master_reset_at=null;saveDb()}

  function excelRowCount(wb){try{const ws=wb.Sheets[db.master.sheet||'MAGAZZINO']||wb.Sheets.MAGAZZINO||wb.Sheets[wb.SheetNames[0]],matrix=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',blankrows:false});const hr=typeof detectMasterHeader==='function'?detectMasterHeader(matrix):0;return Math.max(0,matrix.length-hr-1)}catch{return 0}}

  async function commitImportedWorkbook(beforeImportAt){if(!pendingImport)return;const p=pendingImport;pendingImport=null;try{const bytes=await p.bytesPromise;if(!db.master?.imported_at||db.master.imported_at===beforeImportAt)return;const wb=p.workbook||XLSX.read(bytes,{type:'array',cellDates:true,cellStyles:true});const importedMaster=clone(db.master),embedded=parseEmbeddedDb(wb);if(embedded){restoreEmbeddedDb(embedded,importedMaster);toast(`Master importato con storico: ${(db.movements||[]).length} movimenti, ${(db.documents||[]).length} scarichi e ${(db.requests||[]).length} richieste.`,'success')}else{resetOperationalHistoryKeepMaster(importedMaster);toast('Master aziendale importato. È stato avviato un nuovo ciclo di lavoro.','success')}
      await idbPut(IDB_MASTER_KEY,bytes);const now=db.master.imported_at||isoNow();writeMeta({fileName:p.name,excelRows:excelRowCount(wb),importedAt:now,lastExportAt:now,lastExportName:'',sourceHasAppData:!!embedded});if(typeof renderMasterStatus==='function')renderMasterStatus();if(typeof renderRegistry==='function')renderRegistry();await renderPanel();
      modal({title:'Master pronto',icon:'✓',body:`<p><b>${html(p.name)}</b> è stato caricato correttamente.</p><p>Da questo momento tutte le operazioni vengono applicate alla giacenza del master. Quando hai finito, usa <b>ESPORTA MASTER AGGIORNATO</b>.</p>${embedded?'<p>Lo storico contenuto nel file è stato ripristinato.</p>':'<p>Questo file non conteneva uno storico app: il registro parte da questa importazione.</p>'}`});
    }catch(e){console.error(e);toast('Impossibile memorizzare il file master: '+(e.message||e),'error');await renderPanel()}}

  function fullArticle(article,size){const a=norm(article),s=norm(size);return s?`${a}-${s}`:a}
  function idKey(article,size,loc,pal){return [norm(article),norm(size),norm(loc),norm(pal)].join('|')}
  function rowKeyFromMaster(raw,c){const p=splitMasterArticleSize(raw[c.article]);return p.article?idKey(p.article,p.size,raw[c.location],raw[c.bancale]):''}
  function touchedKeys(){const set=new Set(),cut=new Date(db.master?.imported_at||0).getTime();for(const m of (db.movements||[])){if(m.cancelled_at)continue;const t=new Date(m.updated_at||m.registered_at||m.operation_at||0).getTime();if(t>=cut)set.add(idKey(m.article_base,m.size,locationOf(m),m.bancale))}return set}

  function currentIdentityMap(){const map=new Map();for(const s of stockBuckets()){if(!VALID_MASTER_STATES.includes(norm(s.state)))continue;const k=idKey(s.article_base,s.size,locationOf(s),s.bancale);if(!map.has(k))map.set(k,{article:norm(s.article_base),size:norm(s.size),location:norm(locationOf(s)),pallet:norm(s.bancale),NUOVO:0,SCARICATO:0,USATO:0});map.get(k)[norm(s.state)]+=Number(s.quantity||0)}return map}

  function setCell(ws,r,c,value,template){const addr=XLSX.utils.encode_cell({r,c}),old=ws[addr]||{},cell={...old};if(template&&!old.s&&template.s)cell.s=clone(template.s);if(template&&!old.z&&template.z)cell.z=template.z;cell.v=value;if(value instanceof Date)cell.t='d';else if(typeof value==='number')cell.t='n';else cell.t='s';delete cell.w;ws[addr]=cell}
  function cloneRowStyle(ws,sourceR,targetR,maxC){for(let c=0;c<=maxC;c++){const src=ws[XLSX.utils.encode_cell({r:sourceR,c})],dst=XLSX.utils.encode_cell({r:targetR,c});if(src?.s&&!ws[dst])ws[dst]={t:'s',v:'',s:clone(src.s),z:src.z}}if(ws['!rows']?.[sourceR]){ws['!rows']=ws['!rows']||[];ws['!rows'][targetR]=clone(ws['!rows'][sourceR])}}
  function extendRef(ws,row,col){const ref=ws['!ref']?XLSX.utils.decode_range(ws['!ref']):{s:{r:0,c:0},e:{r:row,c:col}};ref.e.r=Math.max(ref.e.r,row);ref.e.c=Math.max(ref.e.c,col);ws['!ref']=XLSX.utils.encode_range(ref);if(ws['!autofilter']?.ref){const af=XLSX.utils.decode_range(ws['!autofilter'].ref);af.e.r=Math.max(af.e.r,row);ws['!autofilter'].ref=XLSX.utils.encode_range(af)}}

  function updateMagazineSheet(wb){const sheetName=db.master?.sheet&&wb.Sheets[db.master.sheet]?db.master.sheet:(wb.Sheets.MAGAZZINO?'MAGAZZINO':wb.SheetNames[0]),ws=wb.Sheets[sheetName];if(!ws)throw new Error('Foglio MAGAZZINO non trovato nel file originale.');const matrix=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:true,blankrows:true}),hr=detectMasterHeader(matrix),headers=(matrix[hr]||[]).map(v=>String(v||'').trim()),c=definitiveMasterColumns(headers);if(!isDefinitiveMaster(c))throw new Error('Il master non ha più la struttura attesa: SCAFFALE/FILA, BANCALE, ARTICOLO, NUOVO, SCARICATO, USATO.');const current=currentIdentityMap(),seen=new Set(),touched=touchedKeys(),today=new Date();today.setHours(0,0,0,0);let lastDataR=hr,maxC=Math.max(c.location,c.bancale,c.article,c.nuovo,c.scaricato,c.usato,c.controlDate||0);
    for(let r=hr+1;r<matrix.length;r++){const raw=matrix[r]||[],key=rowKeyFromMaster(raw,c);if(!key)continue;lastDataR=r;if(seen.has(key))continue;seen.add(key);const q=current.get(key)||{NUOVO:0,SCARICATO:0,USATO:0};setCell(ws,r,c.nuovo,Number(q.NUOVO||0));setCell(ws,r,c.scaricato,Number(q.SCARICATO||0));setCell(ws,r,c.usato,Number(q.USATO||0));if(c.controlDate>=0&&touched.has(key))setCell(ws,r,c.controlDate,today)}
    const newItems=[...current.entries()].filter(([k])=>!seen.has(k)).sort((a,b)=>(a[1].location+a[1].pallet+a[1].article+a[1].size).localeCompare(b[1].location+b[1].pallet+b[1].article+b[1].size));let r=lastDataR;for(const [key,item] of newItems){r++;cloneRowStyle(ws,lastDataR,r,maxC);const templateC=col=>ws[XLSX.utils.encode_cell({r:lastDataR,c:col})];setCell(ws,r,c.location,item.location,templateC(c.location));setCell(ws,r,c.bancale,item.pallet,templateC(c.bancale));setCell(ws,r,c.article,fullArticle(item.article,item.size),templateC(c.article));setCell(ws,r,c.nuovo,Number(item.NUOVO||0),templateC(c.nuovo));setCell(ws,r,c.scaricato,Number(item.SCARICATO||0),templateC(c.scaricato));setCell(ws,r,c.usato,Number(item.USATO||0),templateC(c.usato));if(c.controlDate>=0)setCell(ws,r,c.controlDate,today,templateC(c.controlDate));extendRef(ws,r,maxC)}return {sheetName,newRows:newItems.length,totalIdentities:current.size}}

  const hdrStyle={font:{bold:true,color:{rgb:'FFFFFF'}},fill:{patternType:'solid',fgColor:{rgb:'4472C4'}},alignment:{horizontal:'center',vertical:'center',wrapText:true},border:{bottom:{style:'thin',color:{rgb:'D9E2F3'}}}};
  const altStyle={fill:{patternType:'solid',fgColor:{rgb:'EAF1F8'}}};
  function makeSheet(headers,rows,widths){const data=[headers,...rows],ws=XLSX.utils.aoa_to_sheet(data);ws['!autofilter']={ref:XLSX.utils.encode_range({s:{r:0,c:0},e:{r:Math.max(0,rows.length),c:headers.length-1}})};ws['!cols']=widths.map(w=>({wch:w}));for(let c=0;c<headers.length;c++){const a=XLSX.utils.encode_cell({r:0,c});ws[a].s=clone(hdrStyle)}for(let r=1;r<=rows.length;r++){if(r%2===0)for(let c=0;c<headers.length;c++){const a=XLSX.utils.encode_cell({r,c});if(ws[a])ws[a].s=clone(altStyle)}}return ws}
  function replaceSheet(wb,name,ws){wb.Sheets[name]=ws;if(!wb.SheetNames.includes(name))wb.SheetNames.push(name)}

  function buildMovementSheet(wb){const h=['DATA / ORA','ID MOVIMENTO','OPERATORE','OPERAZIONE','ARTICOLO','TAGLIA','QUANTITÀ','STATO','FILA / SCAFFALE','BANCALE','DESTINAZIONE','DOCUMENTO','RICHIESTA','NOTE','STATO MOVIMENTO','ANNULLATO IL'];const rows=[...(db.movements||[])].sort((a,b)=>new Date(a.registered_at||a.operation_at||0)-new Date(b.registered_at||b.operation_at||0)).map(m=>[dateTimeText(m.registered_at||m.operation_at),m.id||'',m.operator||'',m.movement_type||'',m.article_base||'',m.size||'',Number(m.quantity||0),m.state||'',locationOf(m)||'',m.bancale||'',m.destination||'',m.document_id||'',m.source_request_id||'',m.note||'',m.cancelled_at?'ANNULLATO':'ATTIVO',dateTimeText(m.cancelled_at)]);replaceSheet(wb,MOV_SHEET,makeSheet(h,rows,[20,25,16,14,24,10,12,14,16,12,18,19,19,34,17,20]))}

  function buildDocumentsSheet(wb){const h=['DOCUMENTO','DATA / ORA','OPERATORE','DESTINAZIONE','STATO DOCUMENTO','RICHIESTA','ARTICOLO','TAGLIA','QUANTITÀ','STATO MERCE','FILA / SCAFFALE','BANCALE','NOTE'];const rows=[];for(const d of [...(db.documents||[])].sort((a,b)=>new Date(a.created_at||0)-new Date(b.created_at||0))){const ms=(d.movement_ids||[]).map(id=>(db.movements||[]).find(m=>m.id===id)).filter(Boolean),active=ms.filter(m=>!m.cancelled_at),docState=!ms.length?'SENZA RIGHE':!active.length?'ANNULLATO':active.length<ms.length?'PARZIALE':'ATTIVO';if(!ms.length)rows.push([d.id,dateTimeText(d.created_at||d.operation_at),d.operator||'',d.destination||'',docState,d.request_id||'','','','','','','',d.note||'']);else for(const m of ms)rows.push([d.id,dateTimeText(d.created_at||d.operation_at),d.operator||m.operator||'',d.destination||m.destination||'',m.cancelled_at?'RIGA ANNULLATA':docState,d.request_id||m.source_request_id||'',m.article_base||'',m.size||'',Number(m.quantity||0),m.state||'',locationOf(m)||'',m.bancale||'',m.note||d.note||''])}replaceSheet(wb,DOC_SHEET,makeSheet(h,rows,[19,20,16,18,18,19,24,10,12,14,16,12,34]))}

  function deliveredQty(req,line){const key=normalizeArticle(line.article_base)+'|'+norm(line.size);let total=0;for(const d of (req.deliveries||[]))for(const i of (d.items||[])){if(i.extra)continue;if(normalizeArticle(i.article_base)+'|'+norm(i.size)===key)total+=Number(i.quantity||0)}return total}
  function buildRequestsSheet(wb){const h=['RICHIESTA','DATA RICHIESTA','DESTINAZIONE','OPERATORE','RIFERIMENTO','STATO','ARTICOLO','TAGLIA','QTA RICHIESTA','QTA CONSEGNATA','QTA RESIDUA','NOTE','SCARICHI COLLEGATI'];const rows=[];for(const r of [...(db.requests||[])].sort((a,b)=>new Date(a.requested_at||0)-new Date(b.requested_at||0))){const docs=(r.deliveries||[]).map(d=>d.documentId).filter(Boolean).join(', ');for(const l of (r.lines||[])){const delivered=deliveredQty(r,l),qty=Number(l.quantity||0);rows.push([r.id||'',dateTimeText(r.requested_at),r.destination||'',r.operator||'',r.reference||'',r.status||'',l.article_base||'',l.size||'',qty,delivered,Math.max(0,qty-delivered),l.note||'',docs])}}replaceSheet(wb,REQ_SHEET,makeSheet(h,rows,[19,20,18,16,20,16,24,10,15,16,14,34,28]))}

  function buildDataSheet(wb,exportedAt){const payload={schema:LM_VERSION,exported_at:exportedAt,db:clone(db)},json=JSON.stringify(payload),chunk=30000,rows=[['SO_WAREHOUSE_APP_DATA_V3'],['SCHEMA',LM_VERSION],['ESPORTATO_IL',exportedAt],['JSON_CHUNKS',Math.ceil(json.length/chunk)]];for(let i=0;i<json.length;i+=chunk)rows.push([json.slice(i,i+chunk)]);const ws=XLSX.utils.aoa_to_sheet(rows);replaceSheet(wb,DATA_SHEET,ws);wb.Workbook=wb.Workbook||{};wb.Workbook.Sheets=Array.isArray(wb.Workbook.Sheets)?wb.Workbook.Sheets:wb.SheetNames.map(name=>({name,Hidden:0}));let idx=wb.SheetNames.indexOf(DATA_SHEET);while(wb.Workbook.Sheets.length<wb.SheetNames.length)wb.Workbook.Sheets.push({name:wb.SheetNames[wb.Workbook.Sheets.length],Hidden:0});if(idx>=0){wb.Workbook.Sheets[idx]=wb.Workbook.Sheets[idx]||{name:DATA_SHEET};wb.Workbook.Sheets[idx].name=DATA_SHEET;wb.Workbook.Sheets[idx].Hidden=2}}

  function outputName(){const original=String(db.master?.filename||'Confezionato_MASTER.xlsx'),stem=original.replace(/\.xlsx$/i,'').replace(/_AGGIORNATO(?:_\d{4}-\d{2}-\d{2}(?:_\d{4})?)?$/i,'');return `${stem}_AGGIORNATO_${fileStamp()}.xlsx`}
  function downloadArray(buf,name){const blob=new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.style.display='none';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(url);a.remove()},1500)}

  async function exportUpdatedMaster(){if(!requireMaster())return false;const btn=document.getElementById('lmExportBtn');if(btn){btn.disabled=true;btn.dataset.old=btn.textContent;btn.textContent='⏳ PREPARO EXCEL…'}try{const bytes=await idbGet(IDB_MASTER_KEY);if(!bytes)throw new Error('Il file Excel originale non è più disponibile sul dispositivo. Reimporta il master prima di esportare.');const wb=XLSX.read(bytes,{type:'array',cellDates:true,cellStyles:true,bookVBA:true});const mag=updateMagazineSheet(wb);buildMovementSheet(wb);buildDocumentsSheet(wb);buildRequestsSheet(wb);const exportedAt=isoNow();buildDataSheet(wb,exportedAt);const out=XLSX.write(wb,{type:'array',bookType:'xlsx',cellStyles:true,compression:true,bookSST:false}),name=outputName();downloadArray(out,name);writeMeta({lastExportAt:exportedAt,lastExportName:name});await renderPanel();const c=recordCounts();toast('Master Excel aggiornato esportato correttamente.','success');await modal({title:'Export completato',icon:'✓',body:`<p>È stato creato:</p><p class="lmFilename">${html(name)}</p><p><b>MAGAZZINO</b> aggiornato${mag.newRows?` · ${mag.newRows} nuove righe aggiunte`:''}<br><b>${MOV_SHEET}</b>: ${c.moves} movimenti<br><b>${DOC_SHEET}</b>: ${c.docs} documenti<br><b>${REQ_SHEET}</b>: ${c.reqs} richieste</p><p>Questo file può sostituire il master precedente e potrà essere reimportato nell’app mantenendo lo storico.</p>`,actions:[{label:'CHIUDI',value:'close',kind:'primary'}]});return true}catch(e){console.error(e);toast('Export non riuscito: '+(e.message||e),'error');await modal({title:'Export non riuscito',icon:'!',body:`<p>${html(e.message||e)}</p><p>Il master attuale non è stato modificato.</p>`,actions:[{label:'CHIUDI',value:'close',kind:'primary'}]});return false}finally{if(btn){btn.disabled=false;btn.textContent=btn.dataset.old||'📤 ESPORTA MASTER AGGIORNATO';delete btn.dataset.old}}}

  async function manage(){if(!currentMasterLoaded())return chooseImport();const m=readMeta(),c=recordCounts(),v=await modal({title:'Gestione Master Excel',icon:'⚙',body:`<p><b>${html(db.master.filename||'Master')}</b></p><p>Importato: ${fmtWhen(db.master.imported_at)}<br>Ultimo export: ${fmtWhen(m.lastExportAt)}<br>Movimenti: ${c.moves} · Scarichi: ${c.docs} · Richieste: ${c.reqs}</p>`,actions:[{label:'CHIUDI',value:'cancel',kind:'soft'},{label:'REIMPORTA / SOSTITUISCI',value:'replace',kind:'primary'},{label:'RIMUOVI DAL DISPOSITIVO',value:'remove',kind:'danger'}]});if(v==='replace')return chooseImport();if(v==='remove')return removeMaster()}

  async function removeMaster(){const dirty=dirtyCount(),v=await modal({title:'Rimuovere il master?',icon:'⚠',body:`<p>Il file Excel memorizzato sul dispositivo verrà scollegato dall’app.</p>${dirty?`<p><b>Attenzione:</b> ci sono ${dirty} modifiche non esportate.</p>`:''}<p>Questa operazione non elimina alcun file già presente sul PC o nella cartella Download.</p>`,actions:[{label:'ANNULLA',value:'cancel',kind:'soft'},{label:'RIMUOVI',value:'remove',kind:'danger'}]});if(v!=='remove')return;db=blankDb();saveDb();clearMeta();await idbDelete(IDB_MASTER_KEY).catch(()=>{});if(typeof renderMasterStatus==='function')renderMasterStatus();if(typeof renderRegistry==='function')renderRegistry();await renderPanel();toast('Master rimosso dal dispositivo.','success')}

  function ensureExportableStates(){for(const p of (typeof importedPhotos!=='undefined'?importedPhotos:[]))for(const g of (p.groups||[]))for(const v of (g.variants||[])){if(Number(v.quantity)>0&&!VALID_MASTER_STATES.includes(norm(v.state))){toast(`Stato ${v.state||'NON_CHIARO'} non esportabile nel master Excel.`,'error');alert(`Prima di confermare scegli per ogni riga uno stato tra NUOVO, SCARICATO o USATO. La riga ${g.article_base||''} ${v.size||''} è impostata su ${v.state||'NON_CHIARO'}.`);return false}}return true}

  const LocalMaster={version:LM_VERSION,chooseImport,exportUpdatedMaster,manage,removeMaster,requireMaster,renderPanel};window.LocalMaster=LocalMaster;

  const masterInput=document.getElementById('masterInput');if(masterInput){masterInput.accept='.xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';masterInput.addEventListener('click',e=>{if(importBypass)return;if(!currentUser){e.preventDefault();openLogin();return}if(currentMasterLoaded()&&dirtyCount()>0){e.preventDefault();chooseImport()}},true);masterInput.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;if(!/\.xlsx$/i.test(f.name)){e.preventDefault();toast('Per questa modalità usa un file Excel .xlsx.','error');return}const bytesPromise=f.arrayBuffer();pendingImport={name:f.name,bytesPromise,workbook:null};bytesPromise.then(b=>{try{pendingImport&&(pendingImport.workbook=XLSX.read(b,{type:'array',cellDates:true,cellStyles:true}))}catch{}})},true)}

  const originalImportMapped=window.importMappedMaster;if(typeof originalImportMapped==='function'){window.importMappedMaster=async function(){const before=db.master?.imported_at||'';originalImportMapped();await new Promise(r=>setTimeout(r,0));await commitImportedWorkbook(before)}}

  for(const fn of ['openOperation','openSearch','openStockEdit','openRequests','openRegistry']){const base=window[fn];if(typeof base==='function')window[fn]=function(...args){if(!requireMaster())return;return base.apply(this,args)}}

  const baseConfirm=window.confirmOperation;if(typeof baseConfirm==='function')window.confirmOperation=function(){if(!requireMaster()||!ensureExportableStates())return;const out=baseConfirm.apply(this,arguments);setTimeout(renderPanel,80);return out};
  const baseStockSave=window.saveStockEdit;if(typeof baseStockSave==='function')window.saveStockEdit=function(){const rows=typeof stockEditRowsDraft!=='undefined'?stockEditRowsDraft:[];for(const r of rows){if(!r.deleted&&Number(r.quantity)>0&&!VALID_MASTER_STATES.includes(norm(r.state))){alert('Per il master Excel puoi usare solo NUOVO, SCARICATO o USATO.');return}}const out=baseStockSave.apply(this,arguments);setTimeout(renderPanel,80);return out};

  const baseSaveDb=window.saveDb;if(typeof baseSaveDb==='function'){window.saveDb=function(){const out=baseSaveDb.apply(this,arguments);setTimeout(renderPanel,0);return out}}

  const oldRenderMaster=window.renderMasterStatus;if(typeof oldRenderMaster==='function'){window.renderMasterStatus=function(){oldRenderMaster();const st=document.getElementById('masterStatus');if(st&&currentMasterLoaded()){const m=readMeta();st.className='status good';st.textContent=`${db.master.filename} · master locale attivo · ${dirtyCount()} modifiche dall’ultimo export${m.lastExportAt?` · ultimo export ${fmtWhen(m.lastExportAt)}`:''}`}const del=document.getElementById('deleteMasterBtn');if(del){del.textContent='RIMUOVI MASTER DAL DISPOSITIVO';del.onclick=()=>LocalMaster.removeMaster()}}}

  const oldSync=window.syncAuthUI;if(typeof oldSync==='function'){window.syncAuthUI=function(){oldSync();setTimeout(renderPanel,0)}}
  const oldShow=window.show;if(typeof oldShow==='function'){window.show=function(id){const out=oldShow.apply(this,arguments);if(id==='home')setTimeout(renderPanel,0);return out}}

  ensurePanel();if(typeof renderMasterStatus==='function')renderMasterStatus();renderPanel();
})();
