(function(){'use strict';
const M=window.M365,U=window.M365Util;if(!M||!U)return;
const TOKEN_KEY='so_m365_tokens_v1',RESULT_KEY='so_m365_oauth_result',REDIRECT='https://raw.githack.com/Mexpy88/audio-grattaevinci/warehouse-ai-live/auth-callback.html',SCOPES='openid profile offline_access Files.ReadWrite';
M.redirectUri=REDIRECT;
function b64url(bytes){let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function randomUrl(n=64){const a=new Uint8Array(n);crypto.getRandomValues(a);return b64url(a)}
async function challenge(verifier){return b64url(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))))}
function tokens(){try{return JSON.parse(sessionStorage.getItem(TOKEN_KEY)||'null')}catch{return null}}
function saveTokens(v){if(v)sessionStorage.setItem(TOKEN_KEY,JSON.stringify(v));else sessionStorage.removeItem(TOKEN_KEY)}
function tenant(){return String(M.cfg.tenant||'organizations').trim()||'organizations'}
function tokenUrl(){return `https://login.microsoftonline.com/${encodeURIComponent(tenant())}/oauth2/v2.0/token`}
async function tokenRequest(params){const res=await fetch(tokenUrl(),{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams(params)});let j={};try{j=await res.json()}catch{}if(!res.ok)throw new Error(j.error_description||j.error||`Microsoft token ${res.status}`);const old=tokens()||{},t={access_token:j.access_token||old.access_token||'',refresh_token:j.refresh_token||old.refresh_token||'',expires_at:Date.now()+Math.max(60,Number(j.expires_in||3600))*1000-90000,scope:j.scope||old.scope||SCOPES};saveTokens(t);return t}
async function setProfile(access){try{const r=await fetch('https://graph.microsoft.com/v1.0/me?$select=id,displayName,userPrincipalName,mail',{headers:{Authorization:'Bearer '+access}});if(!r.ok)return;const p=await r.json();M.account={homeAccountId:p.id||p.userPrincipalName,username:p.userPrincipalName||p.mail||M.cfg.loginHint||'',name:p.displayName||p.userPrincipalName||''};U.saveObj(U.ACCOUNT_KEY,M.account)}catch(e){console.warn('Profilo Microsoft non letto',e)}}
async function refreshToken(t){if(!t?.refresh_token)throw new Error('Accesso Microsoft richiesto.');const n=await tokenRequest({client_id:String(M.cfg.clientId).trim(),grant_type:'refresh_token',refresh_token:t.refresh_token,scope:SCOPES});await setProfile(n.access_token);return n.access_token}
function waitCallback(state,popup){return new Promise((resolve,reject)=>{let done=false,bc=null,timer=null,poll=null;const finish=(err,v)=>{if(done)return;done=true;clearTimeout(timer);clearInterval(poll);try{bc?.close()}catch{}window.removeEventListener('message',onMsg);try{localStorage.removeItem(RESULT_KEY)}catch{}if(err)reject(err);else resolve(v)};const accept=r=>{if(!r||r.type!=='so-m365-auth-result')return;if(r.state!==state)return;if(r.error)return finish(new Error(r.error_description||r.error));if(!r.code)return;finish(null,r.code)};const onMsg=e=>{if(e.origin===location.origin)accept(e.data)};window.addEventListener('message',onMsg);try{bc=new BroadcastChannel('so_m365_auth');bc.onmessage=e=>accept(e.data)}catch{}try{localStorage.removeItem(RESULT_KEY)}catch{}poll=setInterval(()=>{try{const raw=localStorage.getItem(RESULT_KEY);if(raw)accept(JSON.parse(raw))}catch{}if(popup?.closed&&!done)finish(new Error('Accesso Microsoft annullato o finestra chiusa.'))},250);timer=setTimeout(()=>finish(new Error('Tempo scaduto durante l’accesso Microsoft.')),180000)})}
M.loginInteractive=async function(){if(!M.isConfigured())throw new Error('Configura prima l’Application (Client) ID Microsoft Entra.');if(!crypto?.subtle)throw new Error('Il browser non supporta la sicurezza PKCE richiesta da Microsoft.');const w=520,h=720,left=Math.max(0,(screen.width-w)/2),top=Math.max(0,(screen.height-h)/2),popup=window.open('about:blank','soMicrosoft365',`popup=yes,width=${w},height=${h},left=${left},top=${top}`);if(!popup)throw new Error('Popup bloccato dal browser. Consenti i popup e riprova.');try{popup.document.title='Microsoft 365';popup.document.body.innerHTML='<div style="font-family:system-ui;padding:30px;text-align:center">Connessione sicura a Microsoft 365…</div>'}catch{}try{const verifier=randomUrl(64),state=randomUrl(24),cc=await challenge(verifier),u=new URL(`https://login.microsoftonline.com/${encodeURIComponent(tenant())}/oauth2/v2.0/authorize`);u.searchParams.set('client_id',String(M.cfg.clientId).trim());u.searchParams.set('response_type','code');u.searchParams.set('redirect_uri',REDIRECT);u.searchParams.set('response_mode','query');u.searchParams.set('scope',SCOPES);u.searchParams.set('code_challenge',cc);u.searchParams.set('code_challenge_method','S256');u.searchParams.set('state',state);if(M.cfg.loginHint)u.searchParams.set('login_hint',M.cfg.loginHint);popup.location.replace(u.toString());const code=await waitCallback(state,popup);try{popup.close()}catch{}const t=await tokenRequest({client_id:String(M.cfg.clientId).trim(),grant_type:'authorization_code',code,redirect_uri:REDIRECT,code_verifier:verifier,scope:SCOPES});await setProfile(t.access_token);return t.access_token}catch(e){try{popup.close()}catch{}throw e}};
M.getToken=async function(interactive=false){let t=tokens();if(t?.access_token&&Number(t.expires_at||0)>Date.now())return t.access_token;if(t?.refresh_token){try{return await refreshToken(t)}catch(e){console.warn('Refresh Microsoft fallito',e);saveTokens(null)}}if(interactive)return M.loginInteractive();throw new Error('Accesso Microsoft richiesto.')};
M.connect=async function(){if(!currentUser){if(typeof openLogin==='function')openLogin();return}if(!M.isConfigured()){if(typeof openM365Config==='function')openM365Config();return}M.setStatus('busy','Accesso sicuro all’account Microsoft aziendale…');try{await M.getToken(true);await M.resolveMaster();await M.createSession();if(typeof M.ensureControlSheet==='function')await M.ensureControlSheet();await M.refreshMaster({silent:true});M.online=true;M.lastSync=new Date();M.setStatus('online');U.toast(`Master online: ${M.master.name}`,'success')}catch(e){console.error(e);M.online=false;M.setStatus('error',U.friendlyError(e));U.toast(U.friendlyError(e),'error')}};
M.silentReconnect=async function(){if(!M.isConfigured()||!M.master)return M.setStatus('offline');const t=tokens();if(!t?.access_token&&!t?.refresh_token)return M.setStatus('offline');try{await M.getToken(false);await M.validateMaster();await M.createSession();if(typeof M.ensureControlSheet==='function')await M.ensureControlSheet();await M.refreshMaster({silent:true});M.online=true;M.lastSync=new Date();M.setStatus('online')}catch(e){console.warn(e);M.online=false;M.setStatus('offline')}};
M.disconnect=async function(){M.online=false;M.account=null;M.sessionId='';saveTokens(null);localStorage.removeItem(U.ACCOUNT_KEY);M.setStatus('offline')};
})();
