(function(){'use strict';
const M=window.M365,U=window.M365Util;if(!M||!U)return;const {norm}=U;
async function ensureHiddenSheet(name,headers){await M.createSession();let sheets=await M.fetchGraph(`${M.workbookBase()}/worksheets`),s=(sheets.value||[]).find(x=>String(x.name).toUpperCase()===name.toUpperCase());if(!s){try{s=await M.fetchGraph(`${M.workbookBase()}/worksheets/add`,{method:'POST',body:JSON.stringify({name})})}catch(e){sheets=await M.fetchGraph(`${M.workbookBase()}/worksheets`);s=(sheets.value||[]).find(x=>String(x.name).toUpperCase()===name.toUpperCase());if(!s)throw e}}const end=String.fromCharCode(64+headers.length);await M.fetchGraph(`${M.workbookBase()}/worksheets('${name}')/range(address='A1:${end}1')`,{method:'PATCH',body:JSON.stringify({values:[headers]})});try{await M.fetchGraph(`${M.workbookBase()}/worksheets/${encodeURIComponent(s.id)}`,{method:'PATCH',body:JSON.stringify({visibility:'VeryHidden'})})}catch{}return s}
M.ensureRequestSheet=async function(){return ensureHiddenSheet('APP_REQUESTS',['ID','UPDATED_AT','STATUS','DESTINATION','OPERATOR','REQUESTED_AT','REFERENCE','JSON'])};
function cloudRequest(req){const copy=typeof structuredClone==='function'?structuredClone(req):JSON.parse(JSON.stringify(req));copy.updated_at=copy.updated_at||new Date().toISOString();copy.draft={allocations:[],extraAllocations:[],note:copy.draft?.note||''};return copy}
M.upsertRequest=async function(req){await this.ensureRequestSheet();const lock=await this.acquireLock();try{const used=await this.fetchGraph(`${this.workbookBase()}/worksheets('APP_REQUESTS')/usedRange(valuesOnly=true)`),vals=used.values||[],idx=vals.findIndex((r,i)=>i>0&&String(r?.[0]||'')===req.id),updated=new Date().toISOString();req.updated_at=updated;const c=cloudRequest(req),row=[req.id,updated,req.status||'',req.destination||'',req.operator||'',req.requested_at||'',req.reference||'',JSON.stringify(c)],excelRow=idx>0?Number(used.rowIndex||0)+idx+1:Math.max(2,Number(used.rowIndex||0)+Number(used.rowCount||0)+1);await this.fetchGraph(`${this.workbookBase()}/worksheets('APP_REQUESTS')/range(address='A${excelRow}:H${excelRow}')`,{method:'PATCH',body:JSON.stringify({values:[row]})});return req}finally{await this.releaseLock(lock).catch(()=>{})}};
M.deleteCloudRequest=async function(req){const copy=cloudRequest(req);copy.deleted_at=new Date().toISOString();copy.status='ELIMINATA';await this.upsertRequest(copy);return copy};
M.syncRequests=async function(){await this.ensureRequestSheet();const used=await this.fetchGraph(`${this.workbookBase()}/worksheets('APP_REQUESTS')/usedRange(valuesOnly=true)`),vals=used.values||[];let changed=false;for(let i=1;i<vals.length;i++){const raw=String(vals[i]?.[7]||'');if(!raw)continue;let r;try{r=JSON.parse(raw)}catch{continue}if(!r?.id)continue;const li=db.requests.findIndex(x=>x.id===r.id);if(r.deleted_at){if(li>=0){db.requests.splice(li,1);changed=true}continue}r.draft={allocations:[],extraAllocations:[],note:r.draft?.note||''};if(li<0){db.requests.push(r);changed=true}else{const local=db.requests[li],rt=new Date(r.updated_at||r.created_at||0).getTime(),lt=new Date(local.updated_at||local.created_at||0).getTime();if(rt>lt){const note=local.draft?.note||r.draft.note||'';db.requests[li]={...r,draft:{allocations:[],extraAllocations:[],note}};changed=true}}}if(changed){db.requests.sort((a,b)=>new Date(b.requested_at||b.created_at||0)-new Date(a.requested_at||a.created_at||0));saveDb()}return changed};
function sig(m,withOp=true){return [withOp?(m.cloud_op_id||''):'',m.movement_type||'',norm(m.article_base),norm(m.size),Number(m.quantity||0),m.state||'',norm(locationOf(m)),norm(m.bancale),m.document_id||'',m.source_request_id||''].join('|')}
M.syncHistory=async function(){await this.ensureControlSheet();const used=await this.fetchGraph(`${this.workbookBase()}/worksheets('APP_CONTROL')/usedRange(valuesOnly=true)`),v=used.values||[];let h=v.findIndex(r=>String(r?.[0]||'').toUpperCase()==='TIMESTAMP'&&String(r?.[1]||'').toUpperCase()==='OPERATORE');if(h<0)return false;const existing=new Set(db.movements.map(x=>sig(x,true))),coreMap=new Map(db.movements.map(x=>[sig(x,false),x]));let changed=false;for(let i=h+1;i<v.length;i++){const r=v[i]||[],type=String(r[2]||'').toUpperCase();if(!['CARICA','SCARICA'].includes(type))continue;const op=String(r[12]||''),m={id:`CLOUD-${Number(used.rowIndex||0)+i+1}-${op||i}`,document_id:String(r[11]||'')||null,source_request_id:String(r[10]||'')||null,movement_type:type,article_base:String(r[3]||'').toUpperCase(),size:String(r[4]||'').toUpperCase(),quantity:Number(r[5]||0),state:String(r[6]||'').toUpperCase(),fila_scaffale:String(r[7]||'').toUpperCase(),fila:String(r[7]||'').toUpperCase(),scaffale:'',bancale:String(r[8]||'').toUpperCase(),destination:String(r[9]||'')||null,operator:String(r[1]||'Microsoft 365'),operation_at:String(r[0]||new Date().toISOString()),registered_at:String(r[0]||new Date().toISOString()),arrival_at:null,updated_at:String(r[0]||new Date().toISOString()),cancelled_at:null,note:'Sincronizzato dal registro Microsoft 365',cloud_op_id:op};const exact=sig(m,true);if(existing.has(exact))continue;const core=sig(m,false),local=coreMap.get(core);if(local&&Math.abs(new Date(local.registered_at||local.operation_at||0).getTime()-new Date(m.registered_at).getTime())<120000){if(!local.cloud_op_id&&op){local.cloud_op_id=op;changed=true}existing.add(exact);continue}db.movements.push(m);existing.add(exact);coreMap.set(core,m);changed=true}if(changed)db.movements.sort((a,b)=>new Date(b.registered_at||b.operation_at||0)-new Date(a.registered_at||a.operation_at||0));const groups=new Map();for(const m of db.movements){if(!m.document_id||m.cancelled_at)continue;if(!groups.has(m.document_id))groups.set(m.document_id,[]);groups.get(m.document_id).push(m)}for(const [id,rows] of groups){if(db.documents.some(d=>d.id===id))continue;const f=rows[0];db.documents.push({id,type:'SCARICO',destination:f.destination||'',operator:f.operator||'',operation_at:f.operation_at,created_at:f.registered_at,movement_ids:rows.map(x=>x.id),request_id:f.source_request_id||null,note:'Sincronizzato da Microsoft 365'});changed=true}if(changed){db.documents.sort((a,b)=>new Date(b.created_at||b.operation_at||0)-new Date(a.created_at||a.operation_at||0));saveDb()}return changed};
M.syncCloudData=async function(){await this.syncRequests();await this.syncHistory();return true};
const baseConnect=M.connect.bind(M);M.connect=async function(){await baseConnect();if(this.isOnline())try{await this.syncCloudData()}catch(e){console.warn('Sincronizzazione dati condivisi incompleta',e);U.toast('Master collegato; sincronizzazione richieste/storico da completare.','warn')}};
const baseSilent=M.silentReconnect.bind(M);M.silentReconnect=async function(){await baseSilent();if(this.isOnline())try{await this.syncCloudData()}catch(e){console.warn('Sync cloud silenziosa incompleta',e)}};
})();
