(function(){'use strict';
const M=window.M365,U=window.M365Util;if(!M||!U)return;
const REDIRECT='https://raw.githack.com/Mexpy88/audio-grattaevinci/warehouse-ai-live/auth-callback.html';
M.redirectUri=REDIRECT;
function esc2(s){return typeof esc==='function'?esc(s):String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function installPanel(){const home=document.getElementById('home');if(!home||document.getElementById('m365Panel'))return;const panel=document.createElement('div');panel.id='m365Panel';panel.className='m365Panel';panel.innerHTML=`<div class="m365Head"><div><div class="m365Eyebrow">MASTER CONDIVISO</div><div id="m365StatusTitle" class="m365Title">Microsoft 365</div></div><span id="m365Badge" class="m365Badge offline">● OFFLINE</span></div><div id="m365StatusSub" class="m365Sub">Connessione al master Excel aziendale.</div><div class="m365Actions"><button id="m365ConnectBtn" class="btn primary" type="button" onclick="m365ConnectAction()">CONNETTI MICROSOFT 365</button><button id="m365RefreshBtn" class="btn soft hidden" type="button" onclick="m365RefreshAction()">↻ AGGIORNA MASTER</button><button id="m365OpenBtn" class="btn soft hidden" type="button" onclick="m365OpenExcel()">EXCEL ONLINE</button><button class="m365Gear" type="button" title="Impostazioni Microsoft 365" onclick="openM365Config()">⚙</button></div>`;const sw=document.getElementById('viewModeSwitch'),hero=home.querySelector('.hero');(sw||hero)?.insertAdjacentElement('afterend',panel);M.setStatus('offline')}
function installDialogs(){if(!document.getElementById('m365ConfigDialog')){const d=document.createElement('dialog');d.id='m365ConfigDialog';d.innerHTML=`<div class="dialogHead"><h2>Microsoft 365</h2><button type="button" onclick="closeM365Config()">×</button></div><p>Configurazione della connessione al master Excel condiviso. Non inserire password o client secret.</p><label>Application (Client) ID<input id="m365ClientId" class="field" autocomplete="off" placeholder="00000000-0000-0000-0000-000000000000"></label><label>Tenant<input id="m365Tenant" class="field" autocomplete="off" value="organizations" placeholder="organizations o Tenant ID"></label><label>Account Microsoft aziendale<input id="m365LoginHint" class="field" autocomplete="off" value="MagazzinoTE@manutencoop.it"></label><label>Nome file master<input id="m365MasterName" class="field" value="Confezionato_MASTER.xlsx"></label><label>Foglio magazzino<input id="m365Worksheet" class="field" value="MAGAZZINO"></label><div class="m365Redirect"><b>Redirect URI da registrare come SPA in Microsoft Entra</b><code id="m365RedirectUri">${REDIRECT}</code><button class="mini" type="button" onclick="copyM365Redirect()">COPIA REDIRECT URI</button></div><div class="status warn">Permesso delegato richiesto: <b>Files.ReadWrite</b>. Questa app è una SPA e non usa né deve contenere un client secret.</div><button class="btn success" type="button" onclick="saveM365Config()">SALVA CONFIGURAZIONE</button><button id="m365DisconnectBtn" class="btn soft" type="button" onclick="m365DisconnectAction()">SCOLLEGA ACCOUNT MICROSOFT</button><button id="m365ForgetBtn" class="btn danger" type="button" onclick="m365ForgetMasterAction()">DIMENTICA MASTER ONLINE</button>`;document.body.appendChild(d)}if(!document.getElementById('m365ChooseDialog')){const d=document.createElement('dialog');d.id='m365ChooseDialog';d.innerHTML=`<div class="dialogHead"><h2>Scegli master</h2><button type="button" onclick="cancelM365Choose()">×</button></div><p>Ho trovato più file con lo stesso nome. Seleziona quello corretto.</p><div id="m365ChooseList"></div>`;document.body.appendChild(d)}}
window.openM365Config=function(){const d=document.getElementById('m365ConfigDialog');if(!d)return;document.getElementById('m365ClientId').value=M.cfg.clientId||'';document.getElementById('m365Tenant').value=M.cfg.tenant||'organizations';document.getElementById('m365LoginHint').value=M.cfg.loginHint||'MagazzinoTE@manutencoop.it';document.getElementById('m365MasterName').value=M.cfg.masterName||'Confezionato_MASTER.xlsx';document.getElementById('m365Worksheet').value=M.cfg.worksheet||'MAGAZZINO';document.getElementById('m365DisconnectBtn').classList.toggle('hidden',!M.account);document.getElementById('m365ForgetBtn').classList.toggle('hidden',!M.master);if(!d.open)d.showModal()};
window.closeM365Config=function(){const d=document.getElementById('m365ConfigDialog');if(d?.open)d.close()};
window.copyM365Redirect=async function(){try{await navigator.clipboard.writeText(REDIRECT);U.toast('Redirect URI copiato.','success')}catch{prompt('Copia il Redirect URI:',REDIRECT)}};
window.saveM365Config=function(){const clientId=document.getElementById('m365ClientId').value.trim(),tenant=document.getElementById('m365Tenant').value.trim()||'organizations',loginHint=document.getElementById('m365LoginHint').value.trim(),masterName=document.getElementById('m365MasterName').value.trim()||'Confezionato_MASTER.xlsx',worksheet=document.getElementById('m365Worksheet').value.trim()||'MAGAZZINO';if(clientId&&!/^[0-9a-fA-F-]{30,40}$/.test(clientId)){alert('Il Client ID Microsoft Entra non sembra valido. Incolla l’Application (Client) ID completo.');return}const changedIdentity=clientId!==M.cfg.clientId||tenant!==M.cfg.tenant;const changedMaster=masterName!==M.cfg.masterName||worksheet!==M.cfg.worksheet;M.cfg={clientId,tenant,loginHint,masterName,worksheet};localStorage.setItem(U.CFG_KEY,JSON.stringify(M.cfg));if(changedIdentity){M.account=null;M.online=false;M.sessionId='';localStorage.removeItem(U.ACCOUNT_KEY);try{sessionStorage.removeItem('so_m365_tokens_v1')}catch{}}if(changedMaster){M.master=null;M.online=false;M.sessionId='';localStorage.removeItem(U.MASTER_KEY)}closeM365Config();M.setStatus('offline');U.toast(clientId?'Configurazione Microsoft 365 salvata.':'Configurazione salvata. Inserisci il Client ID per collegare Microsoft 365.','success')};
window.m365ConnectAction=async function(){if(!currentUser){openLogin();return}if(!M.isConfigured()){openM365Config();return}if(M.isOnline()){openM365Config();return}await M.connect()};
window.m365RefreshAction=async function(){if(!M.isOnline())return M.connect();try{await M.refreshMaster();}catch(e){M.setStatus('error',U.friendlyError(e));U.toast(U.friendlyError(e),'error')}};
window.m365OpenExcel=function(){if(M.master?.webUrl)window.open(M.master.webUrl,'_blank','noopener')};
window.m365DisconnectAction=async function(){if(!confirm('Scollegare l’account Microsoft da questo dispositivo? Il file Excel online non verrà modificato.'))return;await M.disconnect();closeM365Config();U.toast('Account Microsoft scollegato da questo dispositivo.','success')};
window.m365ForgetMasterAction=function(){if(!confirm('Dimenticare il collegamento a questo master? Il file Excel su OneDrive NON verrà eliminato.'))return;M.forgetMaster();closeM365Config();U.toast('Collegamento locale al master dimenticato.','success')};
let chooseResolve=null;window.M365ChooseMaster=function(items){installDialogs();const d=document.getElementById('m365ChooseDialog'),list=document.getElementById('m365ChooseList');list.innerHTML=items.map((x,i)=>`<button class="m365File" type="button" onclick="selectM365Choose(${i})"><b>${esc2(x.name)}</b><small>${esc2(x.parentReference?.path||x.remoteItem?.parentReference?.path||x.webUrl||'')}</small></button>`).join('');window.__m365ChooseItems=items;if(!d.open)d.showModal();return new Promise((res,rej)=>{chooseResolve={res,rej}})};window.selectM365Choose=function(i){const x=window.__m365ChooseItems?.[i],d=document.getElementById('m365ChooseDialog');if(d?.open)d.close();if(x&&chooseResolve?.res)chooseResolve.res(x);chooseResolve=null};window.cancelM365Choose=function(){const d=document.getElementById('m365ChooseDialog');if(d?.open)d.close();if(chooseResolve?.rej)chooseResolve.rej(new Error('Selezione master annullata.'));chooseResolve=null};
installPanel();installDialogs();M.setStatus('offline');setTimeout(()=>M.silentReconnect?.(),250);
})();
