(function(){'use strict';
const M=window.M365,U=window.M365Util;if(!M||!U)return;const {norm,colLetter,lineIdentity,sleep}=U;
const CONTROL_HEADERS=['TIMESTAMP','OPERATORE','TIPO','ARTICOLO','TAGLIA','QTA','STATO','FILA_SCAFFALE','BANCALE','DESTINAZIONE','RICHIESTA','DOCUMENTO','OP_ID'];
function today(){return new Date().toLocaleDateString('it-IT')}
function rnum(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function maxLocal(kind){const re=new RegExp('^'+kind+'-\\d{4}-(\\d+)$','i'),ids=kind==='RQ'?(db.requests||[]).map(x=>x.id):(db.documents||[]).map(x=>x.id);let m=kind==='RQ'?Number(db.counters?.request||0):Number(db.counters?.scarico||0);for(const id of ids){const x=String(id||'').match(re);if(x)m=Math.max(m,Number(x[1]||0))}return Math.max(0,Math.floor(m||0))}
M.ensureControlSheet=async function(){await this.createSession();let sheets=await this.fetchGraph(`${this.workbookBase()}/worksheets`),c=(sheets.value||[]).find(s=>String(s.name).toUpperCase()==='APP_CONTROL'),created=false;if(!c){try{c=await this.fetchGraph(`${this.workbookBase()}/worksheets/add`,{method:'POST',body:JSON.stringify({name:'APP_CONTROL'})});created=true}catch(e){sheets=await this.fetchGraph(`${this.workbookBase()}/worksheets`);c=(sheets.value||[]).find(s=>String(s.name).toUpperCase()==='APP_CONTROL');if(!c)throw e}}
let ctl={values:[]},hdr={values:[]};try{[ctl,hdr]=await Promise.all([this.fetchGraph(`${this.workbookBase()}/worksheets('APP_CONTROL')/range(address='A1:B5')`),this.fetchGraph(`${this.workbookBase()}/worksheets('APP_CONTROL')/range(address='A7:M7')`)])}catch{}const v=ctl.values||[],labels=['LOCK_OWNER','LOCK_UNTIL','SC_COUNTER','RQ_COUNTER','VERSION'],valid=labels.every((x,i)=>String(v?.[i]?.[0]||'').toUpperCase()===x),owner=valid?String(v?.[0]?.[1]||''):'',until=valid?rnum(v?.[1]?.[1],0):0,oldSc=valid?rnum(v?.[2]?.[1],0):0,oldRq=valid?rnum(v?.[3]?.[1],0):0,sc=Math.max(oldSc,maxLocal('SC')),rq=Math.max(oldRq,maxLocal('RQ')),headerOk=CONTROL_HEADERS.every((x,i)=>String(hdr.values?.[0]?.[i]||'').toUpperCase()===x);
if(created||!valid){await this.fetchGraph(`${this.workbookBase()}/worksheets('APP_CONTROL')/range(address='A1:B5')`,{method:'PATCH',body:JSON.stringify({values:[['LOCK_OWNER',owner],['LOCK_UNTIL',until],['SC_COUNTER',sc],['RQ_COUNTER',rq],['VERSION',2]]})})}else{if(sc>oldSc)await this.controlRange('B3','PATCH',[[sc]]);if(rq>oldRq)await this.controlRange('B4','PATCH',[[rq]]);if(rnum(v?.[4]?.[1],0)!==2)await this.controlRange('B5','PATCH',[[2]])}if(!headerOk)await this.fetchGraph(`${this.workbookBase()}/worksheets('APP_CONTROL')/range(address='A7:M7')`,{method:'PATCH',body:JSON.stringify({values:[CONTROL_HEADERS]})});if(created||String(c.visibility||'').toLowerCase()!=='veryhidden')try{await this.fetchGraph(`${this.workbookBase()}/worksheets/${encodeURIComponent(c.id)}`,{method:'PATCH',body:JSON.stringify({visibility:'VeryHidden'})})}catch{}};
M.acquireLock=async function(){await this.ensureControlSheet();const token=`${currentUser||'OP'}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;for(let a=0;a<30;a++){const r=await this.controlRange('B1:B2'),owner=String(r.values?.[0]?.[0]||''),until=Number(r.values?.[1]?.[0]||0);if(owner&&owner!==token&&until>Date.now()){await sleep(350+Math.random()*650);continue}await this.controlRange('B1:B2','PATCH',[[token],[Date.now()+120000]]);await sleep(240);let v=await this.controlRange('B1:B2');if(String(v.values?.[0]?.[0]||'')===token){await sleep(260);v=await this.controlRange('B1:B2');if(String(v.values?.[0]?.[0]||'')===token){this._lockToken=token;return {token}}}await sleep(300+Math.random()*500)}throw new Error('Il master è occupato da un altro operatore. Riprova tra qualche secondo.')};
M.renewLock=async function(){const token=this._lockToken;if(!token)return;try{const r=await this.controlRange('B1:B2');if(String(r.values?.[0]?.[0]||'')!==token)throw new Error('Lock Microsoft 365 perso durante la scrittura.');await this.controlRange('B2','PATCH',[[Date.now()+120000]])}catch(e){console.warn(e);throw e}};
M.releaseLock=async function(lock){if(!lock?.token)return;try{const r=await this.controlRange('B1:B2');if(String(r.values?.[0]?.[0]||'')===lock.token)await this.controlRange('B1:B2','PATCH',[[''],[0]])}finally{if(this._lockToken===lock.token)this._lockToken=''}};
M.nextCloudId=async function(kind){const k=String(kind||'').toUpperCase()==='RQ'?'RQ':'SC',cell=k==='RQ'?'B4':'B3';await this.createSession();const lock=await this.acquireLock();try{const r=await this.controlRange(cell),n=Math.max(maxLocal(k),Math.max(0,Math.floor(rnum(r.values?.[0]?.[0],0))))+1;await this.controlRange(cell,'PATCH',[[n]]);if(k==='RQ')db.counters.request=Math.max(Number(db.counters.request||0),n);else db.counters.scarico=Math.max(Number(db.counters.scarico||0),n);saveDb();return `${k}-${new Date().getFullYear()}-${String(n).padStart(5,'0')}`}finally{await this.releaseLock(lock).catch(()=>{})}};
const basePatch=M.patchCell;M.patchCell=async function(row,relCol,value){await basePatch.call(this,row,relCol,value);const dc=this.cache?.hm?.map?.date;if(dc>=0&&dc!==relCol){const abs=Number(this.cache.range.columnIndex||0)+dc,address=`${colLetter(abs)}${row}`;await this.fetchGraph(`${this.sheetPath()}/range(address='${address}')`,{method:'PATCH',body:JSON.stringify({values:[[today()]]})})}await this.renewLock()};
M.addCloudRow=async function(line,state,qty){const hm=this.cache.hm,len=Math.max((this.cache.values[hm.row]||[]).length,Math.max(...Object.values(hm.map).filter(x=>x>=0))+1),v=new Array(len).fill('');v[hm.map.location]=norm(line.fila_scaffale||line.fila);v[hm.map.pallet]=norm(line.bancale);v[hm.map.article]=U.fullCode(line);if(hm.map.NUOVO>=0)v[hm.map.NUOVO]=state==='NUOVO'?qty:0;if(hm.map.SCARICATO>=0)v[hm.map.SCARICATO]=state==='SCARICATO'?qty:0;if(hm.map.USATO>=0)v[hm.map.USATO]=state==='USATO'?qty:0;if(hm.map.date>=0)v[hm.map.date]=today();if(this.table){const tid=encodeURIComponent(this.table.id||this.table.name);await this.fetchGraph(`${this.workbookBase()}/tables/${tid}/rows/add`,{method:'POST',body:JSON.stringify({index:null,values:[v]})})}else{const er=Number(this.cache.range.rowIndex||0)+this.cache.values.length+1,start=Number(this.cache.range.columnIndex||0),address=`${colLetter(start)}${er}:${colLetter(start+len-1)}${er}`;await this.fetchGraph(`${this.sheetPath()}/range(address='${address}')`,{method:'PATCH',body:JSON.stringify({values:[v]})})}await this.renewLock()};
M.appendLog=async function(groups){try{await this.renewLock();const used=await this.fetchGraph(`${this.workbookBase()}/worksheets('APP_CONTROL')/usedRange(valuesOnly=true)`),row=Math.max(8,Number(used.rowIndex||0)+Number(used.rowCount||0)+1),opDefault=`OP-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,values=groups.map(g=>{const id=lineIdentity(g);return [new Date().toISOString(),currentUser||'',g.delta>=0?'CARICA':'SCARICA',id.article,id.size,Math.abs(g.delta),g.state,norm(g.fila_scaffale||g.fila),norm(g.bancale),g.destination||'',g.source_request_id||'',g.document_id||'',g.cloud_op_id||opDefault]}),end=row+values.length-1;await this.fetchGraph(`${this.workbookBase()}/worksheets('APP_CONTROL')/range(address='A${row}:M${end}')`,{method:'PATCH',body:JSON.stringify({values})})}catch(e){console.warn('Log cloud non scritto:',e)}};
})();
