import fs from 'node:fs';
import zlib from 'node:zlib';
import crypto from 'node:crypto';
import vm from 'node:vm';

const loader=fs.readFileSync('index.html','utf8');
const data=loader.match(/const DATA='([^']+)'/)?.[1];
const expected=loader.match(/EXPECTED='([a-f0-9]{64})'/)?.[1];
if(!data||!expected)throw new Error('Loader NOVA incompleto');
const html=zlib.gunzipSync(Buffer.from(data,'base64')).toString('utf8');
const actual=crypto.createHash('sha256').update(html).digest('hex');
if(actual!==expected)throw new Error(`SHA mismatch: ${actual} != ${expected}`);
if(actual!=='b76b0db9269db61e793254961fbfdf96c81311d2e5b01e26e2b0978819190481')throw new Error('Release hash inatteso');
const must=['data-action="login" aria-label="Accedi a Magazzino Teramo"','<span>MAGAZZINO</span><span>TERAMO</span>',"top.classList.toggle('hidden',!logged)","document.body.classList.toggle('guest-mode',!logged)",'isPhoneViewport(){',"mode==='desktop'&&!this.isPhoneViewport()","matchMedia('(max-width: 700px)')",'body.desktop-mode .app-view{width:100%;max-width:100%}','.view-btn{display:none}','.master-name{min-width:0;overflow:hidden}','overflow-x:hidden','.app-view{width:100%;max-width:920px;min-width:0','.guest-mode .app-view{max-width:none;min-height:100dvh','.landing>img{display:block;','.landing-card{appearance:none;'];
for(const token of must)if(!html.includes(token))throw new Error(`Contratto mancante: ${token}`);
const a=html.indexOf('landing(){return'),b=html.indexOf('sectionTitle(',a),landing=html.slice(a,b);
for(const old of ['Gestione Magazzino','Applicazione pulita','MAGAZZINO NOVA','>ACCEDI<'])if(landing.includes(old))throw new Error(`Contenuto landing legacy: ${old}`);
for(const forbidden of ['MutationObserver','setInterval(','goods-receipt-v1.js','goods-receipt-v2-fix.js','role-dashboard-v1.js','premium-dashboard-v2.js','activity-daily-filter-v1.js','TEMP_DO_NOT_USE'])if(html.includes(forbidden))throw new Error(`Residuo/anti-pattern vietato: ${forbidden}`);
const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
if(!scripts.length)throw new Error('Script NOVA assente');
for(let i=0;i<scripts.length;i++)new vm.Script(scripts[i],{filename:`nova-inline-${i}.js`});
const loaderScripts=[...loader.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
for(let i=0;i<loaderScripts.length;i++)new vm.Script(loaderScripts[i],{filename:`nova-loader-${i}.js`});
console.log('NOVA gzip package integrity + mobile/login contracts: OK');
console.log(`NOVA standalone SHA256: ${actual}`);
